//! Per-release data tables (auto-generated by tools/transcode_data_tables.py).

pub mod common_data;
pub mod amiga;
pub mod gba_usa;
pub mod genesis_europe;
pub mod msdos;
pub mod snes;
pub mod symbian_demo;

/// Release-agnostic bundle of per-release data tables.
/// One `RELEASE_DATA` const exists in each release module.
pub struct ReleaseData {
    pub slug: &'static str,
    pub stage_titles: &'static [&'static str],
    pub known_labels: &'static [(u32, &'static [(u32, &'static str)])],
    pub possibly_unused_codeblocks: &'static [(u32, &'static [u32])],
    pub labeled_cinematic_entries: &'static [(u32, &'static [(u32, &'static str)])],
    /// Per-stage variable-name aliases for general-purpose vars
    /// (0x00..0xDF) that are conventionally used for one specific
    /// role in a specific stage. The disassembler emits the alias
    /// instead of `[0xNN]` when looking at the listed stage, and
    /// also emits an `<NAME> EQU 0x<NN>` declaration in the listing
    /// header so the assembler can round-trip the source. Engine-
    /// managed special-purpose vars (0xE0..0xFF and a handful at
    /// 0x3C/0x54/0x67/0xDA/0xDC) are stage-invariant and live in
    /// `disasm::SPECIAL_PURPOSE_VARS` instead.
    ///
    /// Outer key: stage index (matches `stage_titles` order).
    /// Inner pairs: `(var_id, alias_name)`.
    pub stage_specific_vars: &'static [(u32, &'static [(u8, &'static str)])],
    pub resource_ids: crate::romset::ResourceIds<'static>,
}

/// Look up a release by slug at run-time.
pub fn by_slug(slug: &str) -> Option<&'static ReleaseData> {
    match slug {
        "amiga" => Some(&amiga::RELEASE_DATA),
        "gba_usa" => Some(&gba_usa::RELEASE_DATA),
        "genesis_europe" => Some(&genesis_europe::RELEASE_DATA),
        "msdos" => Some(&msdos::RELEASE_DATA),
        // SNES Europe and USA share the same memory layout / level
        // tables — same chunk offsets, same labels — so `snes-eu`
        // reuses the `snes` data tables with a different cartridge
        // filename. Verified by round-trip on the cached EU ROM.
        "snes" | "snes-eu" | "snes_eu" => Some(&snes::RELEASE_DATA),
        "symbian_demo" => Some(&symbian_demo::RELEASE_DATA),
        _ => None,
    }
}
