//! Per-release data tables (auto-generated by tools/transcode_data_tables.py).

pub mod common_data;
pub mod amiga;
pub mod gba_usa;
pub mod genesis_europe;
pub mod msdos;
pub mod snes;
pub mod symbian_demo;
