#!/usr/bin/env python3
"""One-shot transcoder: convert the Python release data tables into Rust source.

Reads the Python modules under `releases/` and emits Rust modules under
`awvm/src/releases/`. The generated Rust files are committed alongside the
sources they came from; running this script regenerates them.

Currently handles:
  releases.common_data.LABELED_CINEMATIC_ENTRIES   -> awvm/src/releases/common_data.rs
  releases.msdos.{MD5_CHECKSUMS, STAGE_TITLES,
                  KNOWN_LABELS,
                  POSSIBLY_UNUSED_CODEBLOCKS,
                  generate_romset/resource_ids}    -> awvm/src/releases/msdos.rs
"""

import importlib
import importlib.util
import os
import sys
import textwrap
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

OUT_DIR = REPO / "awvm" / "src" / "releases"
OUT_DIR.mkdir(parents=True, exist_ok=True)


def rust_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_known_labels(name, data):
    """data: dict[int, dict[int, str]] -> Rust slice-of-(level, slice-of-(addr, name))."""
    lines = [f"pub const {name}: &[(u32, &[(u32, &str)])] = &["]
    for level in sorted(data.keys()):
        lines.append(f"    ({level}, &[")
        for addr in sorted(data[level].keys()):
            lines.append(f"        (0x{addr:04X}, {rust_str(data[level][addr])}),")
        lines.append("    ]),")
    lines.append("];")
    return "\n".join(lines)


def emit_unused_codeblocks(name, data):
    """data: dict[int, list[int]] -> Rust slice-of-(level, slice-of-addr)."""
    lines = [f"pub const {name}: &[(u32, &[u32])] = &["]
    for level in sorted(data.keys()):
        addrs = sorted(data[level])
        if addrs:
            inner = ", ".join(f"0x{a:04X}" for a in addrs)
            lines.append(f"    ({level}, &[{inner}]),")
        else:
            lines.append(f"    ({level}, &[]),")
    lines.append("];")
    return "\n".join(lines)


def emit_string_array(name, items):
    lines = [f"pub const {name}: &[&str] = &["]
    for s in items:
        lines.append(f"    {rust_str(s)},")
    lines.append("];")
    return "\n".join(lines)


def emit_resource_ids(name, ids_dict):
    lines = [f"pub mod {name} {{"]
    for key in ["bytecode", "screen", "music", "sample", "palette", "cinematic", "video2"]:
        items = ids_dict.get(key, [])
        inner = ", ".join(f"0x{a:02X}" for a in items)
        lines.append(f"    pub const {key.upper()}: &[u8] = &[{inner}];")
    lines.append("}")
    return "\n".join(lines)


def emit_md5(name, items):
    lines = [f"pub const {name}: &[(&str, &str)] = &["]
    for k in sorted(items.keys()):
        lines.append(f"    ({rust_str(k)}, {rust_str(items[k])}),")
    lines.append("];")
    return "\n".join(lines)


def header(srcfile):
    return textwrap.dedent(f"""\
        // GENERATED BY tools/transcode_data_tables.py — DO NOT EDIT BY HAND.
        // Source: {srcfile}
        // Re-run that script to refresh.
        """)


RELEASES = [
    ("amiga", "releases.amiga.amiga", "releases/amiga/amiga.py", True),
    ("gba_usa", "releases.gba_usa.gba_usa", "releases/gba_usa/gba_usa.py", True),
    (
        "genesis_europe",
        "releases.genesis_europe.genesis_europe",
        "releases/genesis_europe/genesis_europe.py",
        True,
    ),
    ("msdos", "releases.msdos.msdos", "releases/msdos/msdos.py", True),
    ("snes", "releases.snes.snes", "releases/snes/snes.py", True),
    (
        "symbian_demo",
        "releases.symbian_demo.symbian_demo",
        "releases/symbian_demo/symbian_demo.py",
        True,
    ),
]


def emit_release_data_const(rel_name, has_resource_ids):
    """Bundle the per-release tables into a ReleaseData struct that the
    Rust disassembler reads at runtime."""
    lines = [
        "/// Bundled per-release tables. Used by the disassembler and",
        "/// release dispatch in the CLI.",
        "pub const RELEASE_DATA: crate::releases::ReleaseData = crate::releases::ReleaseData {",
        f"    slug: {rust_str(rel_name)},",
        "    stage_titles: STAGE_TITLES,",
        "    known_labels: KNOWN_LABELS,",
        "    possibly_unused_codeblocks: POSSIBLY_UNUSED_CODEBLOCKS,",
        "    labeled_cinematic_entries: LABELED_CINEMATIC_ENTRIES_OVERRIDE,",
    ]
    if has_resource_ids:
        lines.append(
            "    resource_ids: crate::romset::ResourceIds {"
        )
        lines.append("        bytecode: resource_ids::BYTECODE,")
        lines.append("        cinematic: resource_ids::CINEMATIC,")
        lines.append("        palette: resource_ids::PALETTE,")
        lines.append("        video2: resource_ids::VIDEO2,")
        lines.append("    },")
    else:
        lines.append(
            "    resource_ids: crate::romset::ResourceIds { bytecode: &[], cinematic: &[], palette: &[], video2: &[] },"
        )
    lines.append("};")
    return "\n".join(lines)


def emit_release(rel_name, mod_path, src_path, has_resource_ids):
    mod = importlib.import_module(mod_path)
    sections = [header(src_path)]
    if hasattr(mod, "MD5_CHECKSUMS"):
        sections.append(emit_md5("MD5_CHECKSUMS", mod.MD5_CHECKSUMS))
    if hasattr(mod, "STAGE_TITLES"):
        sections.append(emit_string_array("STAGE_TITLES", mod.STAGE_TITLES))
    else:
        sections.append("pub const STAGE_TITLES: &[&str] = &[];")
    if hasattr(mod, "KNOWN_LABELS"):
        sections.append(emit_known_labels("KNOWN_LABELS", mod.KNOWN_LABELS))
    else:
        sections.append("pub const KNOWN_LABELS: &[(u32, &[(u32, &str)])] = &[];")
    if hasattr(mod, "POSSIBLY_UNUSED_CODEBLOCKS"):
        sections.append(
            emit_unused_codeblocks(
                "POSSIBLY_UNUSED_CODEBLOCKS", mod.POSSIBLY_UNUSED_CODEBLOCKS
            )
        )
    else:
        sections.append("pub const POSSIBLY_UNUSED_CODEBLOCKS: &[(u32, &[u32])] = &[];")
    if hasattr(mod, "LABELED_CINEMATIC_ENTRIES"):
        # Some releases re-use common_data entries via .get(...) calls. Materialise
        # whatever the resolved dict looks like at import time.
        sections.append(
            emit_known_labels(
                "LABELED_CINEMATIC_ENTRIES_OVERRIDE",
                {
                    lvl: dict(v)
                    for lvl, v in mod.LABELED_CINEMATIC_ENTRIES.items()
                    if isinstance(v, dict) and v
                },
            )
        )
    else:
        sections.append("pub const LABELED_CINEMATIC_ENTRIES_OVERRIDE: &[(u32, &[(u32, &str)])] = &[];")
    if has_resource_ids and hasattr(mod, "resource_ids"):
        sections.append(emit_resource_ids("resource_ids", mod.resource_ids))
    sections.append(emit_release_data_const(rel_name, has_resource_ids and hasattr(mod, "resource_ids")))
    out = OUT_DIR / f"{rel_name}.rs"
    out.write_text("\n\n".join(sections) + "\n", encoding="utf-8")
    print(f"wrote {out.relative_to(REPO)}")


def main():
    cd = importlib.import_module("releases.common_data")
    out = OUT_DIR / "common_data.rs"
    out.write_text(
        header("releases/common_data/__init__.py")
        + "\n"
        + emit_known_labels("LABELED_CINEMATIC_ENTRIES", cd.LABELED_CINEMATIC_ENTRIES)
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {out.relative_to(REPO)}")

    for rel in RELEASES:
        emit_release(*rel)

    # Refresh mod.rs to expose the new modules.
    mod_lines = [
        "//! Per-release data tables (auto-generated by tools/transcode_data_tables.py).",
        "",
        "pub mod common_data;",
    ]
    for rel_name, *_ in RELEASES:
        mod_lines.append(f"pub mod {rel_name};")
    mod_lines.append("")
    mod_lines.append("/// Release-agnostic bundle of per-release data tables.")
    mod_lines.append("/// One `RELEASE_DATA` const exists in each release module.")
    mod_lines.append("pub struct ReleaseData {")
    mod_lines.append("    pub slug: &'static str,")
    mod_lines.append("    pub stage_titles: &'static [&'static str],")
    mod_lines.append("    pub known_labels: &'static [(u32, &'static [(u32, &'static str)])],")
    mod_lines.append("    pub possibly_unused_codeblocks: &'static [(u32, &'static [u32])],")
    mod_lines.append("    pub labeled_cinematic_entries: &'static [(u32, &'static [(u32, &'static str)])],")
    mod_lines.append("    pub resource_ids: crate::romset::ResourceIds<'static>,")
    mod_lines.append("}")
    mod_lines.append("")
    mod_lines.append("/// Look up a release by slug at run-time.")
    mod_lines.append("pub fn by_slug(slug: &str) -> Option<&'static ReleaseData> {")
    mod_lines.append("    match slug {")
    for rel_name, *_ in RELEASES:
        mod_lines.append(f"        \"{rel_name}\" => Some(&{rel_name}::RELEASE_DATA),")
    mod_lines.append("        _ => None,")
    mod_lines.append("    }")
    mod_lines.append("}")
    (OUT_DIR / "mod.rs").write_text("\n".join(mod_lines) + "\n", encoding="utf-8")
    print(f"wrote {(OUT_DIR / 'mod.rs').relative_to(REPO)}")


if __name__ == "__main__":
    main()
