#!/usr/bin/env python3
"""One-shot transcoder: convert the Python release data tables into Rust source.

Reads the Python modules under `releases/` and emits Rust modules under
`awvm/src/releases/`. The generated Rust files are committed alongside the
sources they came from; running this script regenerates them.

Currently handles:
  releases.common_data.LABELED_CINEMATIC_ENTRIES   -> awvm/src/releases/common_data.rs
  releases.msdos.{MD5_CHECKSUMS, STAGE_TITLES,
                  KNOWN_LABELS,
                  POSSIBLY_UNUSED_CODEBLOCKS,
                  generate_romset/resource_ids}    -> awvm/src/releases/msdos.rs
"""

import importlib
import importlib.util
import os
import sys
import textwrap
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

OUT_DIR = REPO / "awvm" / "src" / "releases"
OUT_DIR.mkdir(parents=True, exist_ok=True)


def rust_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_known_labels(name, data):
    """data: dict[int, dict[int, str]] -> Rust slice-of-(level, slice-of-(addr, name))."""
    lines = [f"pub const {name}: &[(u32, &[(u32, &str)])] = &["]
    for level in sorted(data.keys()):
        lines.append(f"    ({level}, &[")
        for addr in sorted(data[level].keys()):
            lines.append(f"        (0x{addr:04X}, {rust_str(data[level][addr])}),")
        lines.append("    ]),")
    lines.append("];")
    return "\n".join(lines)


def emit_unused_codeblocks(name, data):
    """data: dict[int, list[int]] -> Rust slice-of-(level, slice-of-addr)."""
    lines = [f"pub const {name}: &[(u32, &[u32])] = &["]
    for level in sorted(data.keys()):
        addrs = sorted(data[level])
        if addrs:
            inner = ", ".join(f"0x{a:04X}" for a in addrs)
            lines.append(f"    ({level}, &[{inner}]),")
        else:
            lines.append(f"    ({level}, &[]),")
    lines.append("];")
    return "\n".join(lines)


def emit_string_array(name, items):
    lines = [f"pub const {name}: &[&str] = &["]
    for s in items:
        lines.append(f"    {rust_str(s)},")
    lines.append("];")
    return "\n".join(lines)


def emit_resource_ids(name, ids_dict):
    lines = [f"pub mod {name} {{"]
    for key in ["bytecode", "screen", "music", "sample", "palette", "cinematic", "video2"]:
        items = ids_dict.get(key, [])
        inner = ", ".join(f"0x{a:02X}" for a in items)
        lines.append(f"    pub const {key.upper()}: &[u8] = &[{inner}];")
    lines.append("}")
    return "\n".join(lines)


def emit_md5(name, items):
    lines = [f"pub const {name}: &[(&str, &str)] = &["]
    for k in sorted(items.keys()):
        lines.append(f"    ({rust_str(k)}, {rust_str(items[k])}),")
    lines.append("];")
    return "\n".join(lines)


def header(srcfile):
    return textwrap.dedent(f"""\
        // GENERATED BY tools/transcode_data_tables.py — DO NOT EDIT BY HAND.
        // Source: {srcfile}
        // Re-run that script to refresh.
        """)


def main():
    # common_data.LABELED_CINEMATIC_ENTRIES
    cd = importlib.import_module("releases.common_data")
    out = OUT_DIR / "common_data.rs"
    out.write_text(
        header("releases/common_data/__init__.py")
        + "\n"
        + emit_known_labels("LABELED_CINEMATIC_ENTRIES", cd.LABELED_CINEMATIC_ENTRIES)
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {out.relative_to(REPO)}")

    # msdos
    msdos = importlib.import_module("releases.msdos.msdos")

    sections = []
    sections.append(header("releases/msdos/msdos.py"))
    sections.append(emit_md5("MD5_CHECKSUMS", msdos.MD5_CHECKSUMS))
    sections.append(emit_string_array("STAGE_TITLES", msdos.STAGE_TITLES))
    sections.append(emit_known_labels("KNOWN_LABELS", msdos.KNOWN_LABELS))
    sections.append(emit_unused_codeblocks("POSSIBLY_UNUSED_CODEBLOCKS", msdos.POSSIBLY_UNUSED_CODEBLOCKS))
    sections.append(emit_resource_ids("resource_ids", msdos.resource_ids))

    out = OUT_DIR / "msdos.rs"
    out.write_text("\n\n".join(sections) + "\n", encoding="utf-8")
    print(f"wrote {out.relative_to(REPO)}")


if __name__ == "__main__":
    main()
